name: new_project_fes
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  persian_datetime_picker: ^3.2.0
  flutter_localizations:
    sdk: flutter
  lucide_icons_flutter: ^3.1.14+2
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700
    - family: BNazanin
      fonts:
        - asset: assets/fonts/BNazanin.ttf
          weight: 700
    - family: BTitr
      fonts:
        - asset: assets/fonts/BTitrBd.ttf   
          weight: 700

  assets:
    - assets/fonts/